version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn pythondjango.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/static
    expose: 
      - 8000
    environment: 
        - SECRET_KEY=$${SECRET_KEY}
        - DJANGO_ALLOWED_HOSTS=$${DJANGO_ALLOWED_HOSTS} 
        - DB_ENGINE=$${DB_ENGINE}
        - DB_NAME=$${DB_NAME}
        - DB_USER=$${DB_USER}
        - DB_PASSWORD=$${DB_PASSWORD}
        - DB_HOST=$${DB_HOST}
        - DB_PORT=$${DB_PORT}
    depends_on: 
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$${POSTGRES_USER}
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD}
      - POSTGRES_DB=$${POSTGRES_DB}

  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - "80:80"
    volumes: 
      - static_volume:/static
    depends_on: 
      - web
    
volumes:
  postgres_data:
  static_volume: