version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn pythondjango.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/static
    expose: 
      - 8000
    env_file:
      - pythondjango/.env
    depends_on: 
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - pythondjango/.env

  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - "80:80"
    volumes: 
      - static_volume:/static
    depends_on: 
      - web
    
volumes:
  postgres_data:
  static_volume: