version: '3.7'

services:
  web:
    build: .
    command: gunicorn pythondjango.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/static
    expose: 
      - 8000
    environment: :
      - SECRET_KEY=${SECRET_KEY}
        DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        DB_ENGINE=${DB_ENGINE}
        DB_NAME=${DB_NAME}
        DB_USER=${DB_USER}
        DB_PASSWORD=${DB_PASSWORD}
        DB_HOST=${DB_HOST}
        DB_PORT=${DB_PORT}
    depends_on: 
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8080:8080"
    volumes: 
      - static_volume:/static
    depends_on: 
      - web
    
volumes:
  postgres_data:
  static_volume: