version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pythondjango/:/usr/src/pythondjango/
    ports:
      - 8000:8000
    env_file:
      - pythondjango/.env
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ajsalemo
      - POSTGRES_PASSWORD=Dudebug1992
      - POSTGRES_DB=todo_db
    env_file:
      - pythondjango/.env

volumes:
  postgres_data: