version: '3.7'

services:
  web:
    build: .
    command: gunicorn pythondjango.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/pythondjango/static
    expose: 
      - 8000
    env_file:
      - ./pythondjango/.env
    depends_on: 
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$DB
    env_file:
      - ./pythondjango/.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes: 
      - static_volume:/pythondjango/static
    depends_on: 
      - web
    
volumes:
  postgres_data:
  static_volume: