version: '3.7'

services:
  web:
    build: .
    command: gunicorn pythondjango.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    env_file:
      - ./pythondjango/.env
    depends_on: 
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./pythondjango/.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on: 
      - web
    
volumes:
  postgres_data: