# Generated by Django 3.0.6 on 2020-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
