# Generated by Django 3.0.6 on 2020-05-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200515_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
